version: "3.7"

services:
  transactions:
    build: ./transactions
    container_name: transactions
    restart: always
    volumes:
      - ./transactions:/src
    environment:
      - APP_NAME=TransactionService
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
