version: "3.7"

services:
  transactions:
    build: 
      context: ./
      dockerfile: ./Dockerfiles/TransactionsDockerfile
    container_name: transactions
    restart: always
    volumes:
      - ./transactions:/src/transactions
      - ./shared:/src/shared
    environment:
      - APP_NAME=TransactionService
    expose:
      - 5000

  mining:
    build:
      context: ./
      dockerfile: ./Dockerfiles/MiningDockerfile
    container_name: mining
    restart: always
    environment:
      - APP_NAME=MiningService
    volumes:
      - ./mining:/src/mining
      - ./shared:/src/shared
    expose:
      - 5000

  nginx:
    build: 
      context: ./
      dockerfile: ./Dockerfiles/NginxDockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mining
      - transactions
