apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: users
  name: users
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: users
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: users
    spec:
      containers:
        - env:
            - name: APP_NAME
              value: UserService
            - name: PYTHONUNBUFFERED
              value: "1"
          image: backend_users
          imagePullPolicy: Never
          name: users
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
