version: "3.7"

services:
  transactions:
    build:
      context: ./backend
      dockerfile: ./Dockerfiles/TransactionsDockerfile
    container_name: transaction-api
    restart: always
    volumes:
      - ./services/transaction-api:/src/transactions-api
      - ./shared:/src/shared
    environment:
      - APP_NAME=TransactionService
      - PYTHONUNBUFFERED=1
    expose:
      - 5000

  vue-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-ui
    ports:
      - "8080:8080"

  mining:
    build:
      context: ./backend
      dockerfile: ./Dockerfiles/MiningDockerfile
    container_name: mining-api
    restart: always
    environment:
      - APP_NAME=MiningService
      - PYTHONUNBUFFERED=1
    volumes:
      - ./services/mining-api:/src/mining-api
      - ./shared:/src/shared
    expose:
      - 5000

  wallet:
    build:
      context: ./backend
      dockerfile: ./Dockerfiles/WalletDockerfile
    container_name: wallet-api
    restart: always
    environment:
      - APP_NAME=WalletService
      - PYTHONUNBUFFERED=1

    volumes:
      - ./services/wallet-api:/src/wallet-api
      - ./shared:/src/shared
    expose:
      - 5000

  users:
    build:
      context: ./backend
      dockerfile: ./Dockerfiles/UsersDockerfile
    container_name: users
    restart: always
    volumes:
      - ./services/users-api:/src/users-api
      - ./shared:/src/shared
    environment:
      - APP_NAME=UserService
      - PYTHONUNBUFFERED=1

    expose:
      - 5000
    depends_on: [mongodb]

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: always
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: bisoncoin
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./backend/services/data:/data/db

  nginx:
    build:
      context: ./backend
      dockerfile: ./Dockerfiles/NginxDockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mining
      - transactions
      - blockchain
      - wallet

  blockchain:
    build:
      context: ./backend
      dockerfile: ./Dockerfiles/BlockchainDockerfile
    container_name: blockchain
    restart: always
    environment:
      - APP_NAME=Blockchain
      - PYTHONUNBUFFERED=1

    volumes:
      - ./blockchain:/src/blockchain
      - ./shared:/src/shared
    expose:
      - 5000

  blockchain-backup:
    build:
      context: ./backend
      dockerfile: ./Dockerfiles/BlockchainDockerfile
    container_name: blockchain-backup
    restart: always
    environment:
      - APP_NAME=Blockchain
      - PYTHONUNBUFFERED=1
      - BACKUP=TRUE
    volumes:
      - ./blockchain:/src/blockchain
      - ./shared:/src/shared
    expose:
      - 5000
